module.exports = {
  release:{
    cluster:{
      canRetry:"true",
      removeNodeErrorCount:"5",
      restoreNodeTimeout:"0",
      defaultSelector:"RR"
    },
    master:{
      host:"47.254.18.39",
      user:"c14",
      password:"shelterC14!",
      database:"shelter",
      acquireTimeout:"10000",
      waitForConnections:"true",
      connectionLimit:"10",
      queueLimit:"0"
    },
    slave:[
      {
        name:"slave1",
        host:"47.254.18.39",
        user:"c14",
        password:"shelterC14!",
        database:"shelter",
        acquireTimeout:"10000",
        waitForConnections:"true",
        connectionLimit:"10",
        queueLimit:"0"
      }
    ]
  },
  dev:{
    cluster:{
      canRetry:"true",
      removeNodeErrorCount:"5",
      restoreNodeTimeout:"0",
      defaultSelector:"RR"
    },
    master:{
      host:"47.254.18.39",
      user:"c14",
      password:"shelterC14!",
      database:"shelter",
      acquireTimeout:"10000",
      waitForConnections:"true",
      connectionLimit:"10",
      queueLimit:"0"
    },
    slave:[
      {
        name:"slave1",
        host:"47.254.18.39",
        user:"c14",
        password:"shelterC14!",
        database:"shelter",
        acquireTimeout:"10000",
        waitForConnections:"true",
        connectionLimit:"10",
        queueLimit:"0"
      },
      {
        name:"slave2",
        host:"47.254.18.39",
        user:"c14",
        password:"shelterC14!",
        database:"shelter",
        acquireTimeout:"10000",
        waitForConnections:"true",
        connectionLimit:"10",
        queueLimit:"0"
      }
    ]
  }
}